### ISSUE TITLE
`Quote reply` doesn't work

### ISSUE THREAD

**Issue by joaomoreno** [hediet/chrome-ext-github-monaco#3]
![image](https://user-images.githubusercontent.com/22350/101750962-0071d200-3ad0-11eb-882c-9e73a99e7f2f.png)

**Comment by hediet** [comment]
Fixed in v0.3.1. Clicking on `Quote reply` will insert the quotation into the first text area with non-zero size. This extension hides the original text area, but monaco creates a non-zero size text area, so github just inserted the quotation there (which is a very fragile implementation tbh).

The fix now simulates a non-zero size for the original text area whenever monaco has a non-zero size. The fix assumes that GitHub preferrs the original text area to monacos internal text area if both have a non-zero size. This is probably due to their order in the DOM.

**Comment by hediet** [comment]
Btw. I still think that a browser extension that integrates gifcap into github might be huge ;)

**Comment by joaomoreno** [comment]
Eheh totally agree! Many thanks for the quick fixes!
